# Generated by Django 4.1.4 on 2022-12-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('production_date', models.CharField(max_length=30, verbose_name='Data de produção')),
                ('terminal', models.IntegerField(blank=True, default=0, null=True, verbose_name='Terminal')),
                ('sequencial', models.IntegerField(blank=True, default=0, null=True, verbose_name='Sequencial')),
                ('batch', models.IntegerField(blank=True, default=0, null=True, verbose_name='Lote')),
                ('type', models.CharField(max_length=30, verbose_name='Tipo')),
                ('liquid', models.IntegerField(blank=True, default=0, null=True, verbose_name='Líquido')),
                ('tara', models.IntegerField(blank=True, default=0, null=True, verbose_name='tara')),
                ('unit_of_measurement', models.CharField(max_length=30, verbose_name='Unidade de Medida')),
                ('client', models.CharField(max_length=30, verbose_name='Cliente')),
                ('product_number', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número do Produto')),
                ('product_name', models.CharField(max_length=30, verbose_name='Nome do Produto')),
                ('sub_total', models.IntegerField(blank=True, default=0, null=True, verbose_name='SubTotal')),
                ('total', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total')),
                ('message', models.CharField(max_length=30, verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ('id',),
            },
        ),
    ]
