# Generated by Django 4.1.4 on 2022-12-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='client',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='message',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='product_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='production_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Data de produção'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='unit_of_measurement',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
