# Generated by Django 4.1.4 on 2023-01-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_lote_client_alter_lote_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('eventID', models.IntegerField(primary_key=True, serialize=False, verbose_name='eventID')),
                ('terminal', models.IntegerField(blank=True, default=0, null=True, verbose_name='Terminal')),
                ('dateTime', models.CharField(blank=True, max_length=30, null=True, verbose_name='Data do Evento')),
                ('evtType', models.IntegerField(blank=True, default=0, null=True, verbose_name='evtType')),
                ('evtCode', models.IntegerField(blank=True, null=True, verbose_name='evtCode')),
                ('evtMessage', models.CharField(blank=True, default=0, max_length=30, null=True, verbose_name='evtMessage')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ('eventID',),
            },
        ),
    ]
