# Generated by Django 4.1.4 on 2023-01-12 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bulk_batchs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulk_Weigths',
            fields=[
                ('weightID', models.IntegerField(primary_key=True, serialize=False, verbose_name='weightID')),
                ('dateTime', models.CharField(blank=True, max_length=30, null=True, verbose_name='Data')),
                ('opType', models.CharField(blank=True, default=0, max_length=30, null=True, verbose_name='Tipo de OP')),
                ('terminal', models.IntegerField(blank=True, default=0, null=True, verbose_name='Terminal')),
                ('net', models.FloatField(blank=True, default=0, null=True, verbose_name='Net')),
                ('tare', models.FloatField(blank=True, max_length=30, null=True, verbose_name='Tara')),
                ('wtUnit', models.CharField(blank=True, default=0, max_length=30, null=True, verbose_name='Unidade')),
                ('stepNumber', models.IntegerField(blank=True, default=0, null=True, verbose_name='stepNumber')),
                ('subtotNumber', models.IntegerField(blank=True, null=True, verbose_name='subtotNumber')),
                ('prodNumber', models.IntegerField(blank=True, null=True, verbose_name='Número de Produção')),
                ('stepTotal', models.FloatField(blank=True, max_length=30, null=True, verbose_name='stepTotal')),
                ('subtotTotal', models.FloatField(blank=True, default=0, null=True, verbose_name='SubTotal')),
                ('prodTotal', models.FloatField(blank=True, default=0, null=True, verbose_name='Produção Total')),
                ('grandTotal', models.FloatField(blank=True, default=0, null=True, verbose_name='grandTotal')),
                ('flow', models.FloatField(blank=True, default=0, null=True, verbose_name='Fluxo')),
                ('flowUnit', models.CharField(blank=True, default=0, max_length=30, null=True, verbose_name='flowUnit')),
                ('batchID', models.IntegerField(blank=True, default=0, null=True, verbose_name='LoteID')),
            ],
            options={
                'verbose_name': 'Peso dos Lotes',
                'verbose_name_plural': 'Bulk peso de Lotes',
                'ordering': ('weightID',),
            },
        ),
    ]
