# Generated by Django 4.1.4 on 2023-01-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bulk_weigths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk_batchs',
            name='targetValueList',
            field=models.CharField(blank=True, default=0, max_length=300, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='bulk_batchs',
            name='userField3',
            field=models.IntegerField(blank=True, null=True, verbose_name='userField3'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='subtotTotal',
            field=models.CharField(blank=True, default=0, max_length=30, null=True, verbose_name='SubTotal'),
        ),
        migrations.AlterField(
            model_name='events',
            name='dateTime',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='events',
            name='evtMessage',
            field=models.CharField(blank=True, default=0, max_length=300, null=True, verbose_name='evtMessage'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de produção'),
        ),
    ]
