# Generated by Django 4.1.4 on 2023-01-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bulk_batchs_targetvaluelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='dateTime',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='production_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Data de produção'),
        ),
    ]
