# Generated by Django 4.1.4 on 2023-01-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_events_datetime_alter_lote_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulk_batchs',
            name='terminal',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Terminal'),
        ),
        migrations.AlterField(
            model_name='bulk_batchs',
            name='userField1',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='userField1'),
        ),
        migrations.AlterField(
            model_name='bulk_batchs',
            name='userField2',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='userField2'),
        ),
        migrations.AlterField(
            model_name='bulk_batchs',
            name='userField3',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='userField3'),
        ),
        migrations.AlterField(
            model_name='bulk_batchs',
            name='userField4',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='userField4'),
        ),
        migrations.AlterField(
            model_name='bulk_batchs',
            name='userField5',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='userField5'),
        ),
        migrations.AlterField(
            model_name='bulk_batchs',
            name='userField6',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='userField6'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='batchID',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='LoteID'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='dateTime',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='flow',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Fluxo'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='flowUnit',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='flowUnit'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='grandTotal',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='grandTotal'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='net',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Net'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='opType',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Tipo de OP'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='prodNumber',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Número de Produção'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='prodTotal',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Produção Total'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='stepNumber',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='stepNumber'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='stepTotal',
            field=models.FloatField(blank=True, default=None, max_length=30, null=True, verbose_name='stepTotal'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='subtotNumber',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='subtotNumber'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='subtotTotal',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='SubTotal'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='tare',
            field=models.FloatField(blank=True, default=None, max_length=30, null=True, verbose_name='Tara'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='terminal',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Terminal'),
        ),
        migrations.AlterField(
            model_name='bulk_weigths',
            name='wtUnit',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='events',
            name='dateTime',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='events',
            name='evtCode',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='evtCode'),
        ),
        migrations.AlterField(
            model_name='events',
            name='evtMessage',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='evtMessage'),
        ),
        migrations.AlterField(
            model_name='events',
            name='evtType',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='evtType'),
        ),
        migrations.AlterField(
            model_name='events',
            name='terminal',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Terminal'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='batch',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='client',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='liquid',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Líquido'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='product_number',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Número do Produto'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='production_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data de produção'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='sequencial',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Sequencial'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='sub_total',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='SubTotal'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tara',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='tara'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='terminal',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Terminal'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='total',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='unit_of_measurement',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
